# Generated by Django 4.2.2 on 2024-02-01 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zotravo_newapp', '0004_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='image',
            field=models.ImageField(null=True, upload_to='city_image/'),
        ),
    ]
