# Generated by Django 4.2.2 on 2024-02-01 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zotravo_newapp', '0005_city_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='city_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='City', to='zotravo_newapp.city'),
        ),
    ]
